version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/sdk/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "genai-obs/maintainers"
    labels:
      - "dependencies"
      - "python"

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/sdk/nodejs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "genai-obs/maintainers"
    labels:
      - "dependencies"
      - "nodejs"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/deploy/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
