global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'genai-local'
    environment: 'dev'

# Load alerting rules
rule_files:
  - /etc/prometheus/rules/genai-rules.yaml

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 10s

  # GenAI metrics from OTel Collector Prometheus exporter
  - job_name: 'genai-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metric_relabel_configs:
      # Preserve GenAI specific labels
      - source_labels: [__name__]
        regex: 'gen_ai_.*'
        action: keep

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']

  # Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
